### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by chromer030** [cmatomic/vlc-3-appimage#1]
Thnx very much for Appimage...
I am on Manjaro linux with kernel 5.4 and on running this appimage i receive Segmentation fault (core dumped).

`[chromer030-Desktop]$ ./VLC_media_player-x86_64.AppImage
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
Segmentation fault (core dumped)
`

My System Info :
Cpu : Intel Core i7 7700
RAM : 8 GB
GPU : igfx

**Comment by cmatomic** [comment]
Thanks  for your answer, what is the desktop version are you using  KDE , GNOME or XFCE ?

**Comment by chromer030** [comment]
Manjaro Cinnamon 18.1.0.
MPV 0.29.1 appimage , working well but this vlc appimage no , and i need this one.
Thnks very much for your work.

**Comment by cmatomic** [comment]
when i tested it was working i'll have to make a new version.
Alternatively you can try this version
https://github.com/cmatomic/Appimage-005

**Comment by chromer030** [comment]
i will test and report , thnx very much

**Comment by cmatomic** [comment]
A new version is available .

**Comment by chromer030** [comment]
i confirm that new version work perfect under kernel 5.4-rc5 in Manjaro Cinnamon.
thanks very much.
