### ISSUE TITLE
Maybe put VLC version in the title?

### ISSUE THREAD

**Issue by probonopd** [cmatomic/vlc-3-appimage#3]
`export VERSION=...` should do the trick.

**Comment by cmatomic** [comment]
Thanks for helping

**Comment by cmatomic** [comment]
> `export VERSION=...` should do the trick.

A new version of the VLC player is available
Thanks again .

**Comment by probonopd** [comment]
Thank you very much. Cool :+1:

**Comment by probonopd** [comment]
Thank you. Added to
https://appimage.github.io/VLC/

:+1:  :100: :1st_place_medal:

**Comment by cmatomic** [comment]
Thanks  very much
