### ISSUE TITLE
Add update information for AppImageUpdate

### ISSUE THREAD

**Issue by probonopd** [cmatomic/vlc-3-appimage#4]
Please consider to add [update information](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information) to the VLC AppImage and ship a .zsync file so that it can be updated using AppImageUpdate. 

E.g., `export UPDATE_INFORMATION="..."` before running `linuxdeploy`. Then also upload the resulting `.zync` file.

@TheAssassin can linuxdeploy "guesstimate" the needed string (like `appimagetool -g`)?

**Comment by cmatomic** [comment]
Thanks has  been updated with .zync file .
